name: Helm lint

on:
  [push, pull_request]

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/slack-chatgpt
          CHART_VALUES: ./charts/slack-chatgpt/values.yaml